### ISSUE TITLE
Feature: add filter for non-cats

### ISSUE THREAD

**Issue by nemoDreamer** [jasonseminara/Cattr#18] opened 2016-01-04 16:02 UTC
This is a disgrace!
I rented this cat, that should have totally been a cat as per description, and it totally was so NOT a cat!
https://cattr-stage.herokuapp.com/#/cats/4

**Comment by jasonseminara** [comment] 2016-01-04 19:46
Thank you for reporting this! While we're still in alpha for this iteration of Cattr, it's still possible to  receive "non-cats". We're working on a fix for this but in the meantime, hope Jocelyn served your mousing needs. Mrs. Wildenstein continues to be an asset to our burgeoning corporation, and since she doesn't age, we regard her as a feature not a bug.

**Comment by nemoDreamer** [comment] 2016-01-05 19:53
:joy_cat:

**Closed as completed** 2016-02-04 16:24 UTC
Labels: wontfix
